<a href="https://colab.research.google.com/github/rohitprajapati7/numpy--array/blob/master/numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#numpy array
import numpy as np
ls=[1,2,3,4]
arr=np.array(ls)
type(arr)
print(arr)

[1 2 3 4]


In [25]:
#now we check how many element in array
arr.shape
#create a multidimesion array
ls1=[1,2,3,4]
ls2=[5,6,7,8]
ls3=[9,10,11,12]
arr=np.array([ls1,ls2,ls3])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
#see shape array that means check no. of row and coloumns
arr.shape

(3, 4)

In [27]:
#reshape the array
arr.reshape(4,3) #change into 4x3 dimesion

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
arr.shape


(3, 4)

In [31]:
arr
arr[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
arr[1:,3:]

array([[ 8],
       [12]])

In [35]:
arr[1:,2:] #always first is row and after , is for coloumn

array([[ 7,  8],
       [11, 12]])

In [39]:
arr[1:,0:3]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [40]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr=np.arange(0,10,step=2) #arange fun is used for arange into the one dimension array and step=2 that means skip two values
arr

array([0, 2, 4, 6, 8])

In [43]:
arr=np.linspace(1,10,50) #linspace fun provide the divided into the same only giving a stating point and ending point or the divided number
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [49]:
#copy function and broadcasting
a=[1,2,3,4]
arr=np.array(a)
type(arr)
arr


array([1, 2, 3, 4])

In [62]:
arr[1:]=5
arr

array([6, 5, 5, 5])

In [63]:
a1=[6,5,8,9]
arr1=np.array(a1)
arr1
arr1[1:]=10
arr1

array([ 6, 10, 10, 10])

In [65]:
arr1=arr.copy() #to help of copy fun copy arr and store the arr1
arr1

array([6, 5, 5, 5])

In [67]:
# some conditions very useful in Exploratory Data Analysis
val=2
arr<2 #check which element less than two

array([False, False, False, False])

In [70]:
arr*2


array([12, 10, 10, 10])

In [71]:
arr/2

array([3. , 2.5, 2.5, 2.5])

In [72]:
arr[arr<45]

array([6, 5, 5, 5])

In [74]:
np.ones(4) #here we write a ones thatwhy it is a print 1

array([1., 1., 1., 1.])

In [76]:
np.ones(4,dtype=int) #change into the int form

array([1, 1, 1, 1])

In [77]:
np.random.rand(3,3)#show me random matrix


array([[0.70563282, 0.49996814, 0.99233004],
       [0.57887716, 0.86996634, 0.80071237],
       [0.18248217, 0.23120424, 0.97859773]])